#[allow(non_snake_case)]
#[derive(Debug, Clone, Copy)]
pub struct VideoConfig {
    cl_gib_allow: bool,
    cl_particle_fallback_base: u8,
    cl_particle_fallback_multiplier: u8,
    cl_ragdoll_maxcount: u8,
    cl_ragdoll_self_collision: bool,
    mat_forceaniso: u8,
    mat_mip_linear: u8,
    stream_memory: u32,
    mat_picmip: u8,
    particle_cpu_level: u8,
    r_createmodeldecals: bool,
    r_decals: u8,
    r_lod_switch_scale: f64,
    shadow_enable: bool,
    shadow_depth_dimen_min: u16,
    shadow_depth_upres_factor_max: u16,
    shadow_maxdynamic: u16,
    ssao_enabled: bool,
    ssao_downsample: bool,
    modeldecals_forceAllowed: bool,
    dvs_enable: bool,
    dvs_gpuframetime_min: u32,
    dvs_gpuframetime_max: u32,
    defaultres: u16,
    defaultresheight: u16,
    fullscreen: bool,
    nowindowborder: bool,
    volumetric_lighting: bool,
    mat_vsync_mode: bool,
    mat_backbuffer_count: u8,
    mat_antialias_mode: u8,
    csm_enabled: bool,
    csm_coverage: u8,
    csm_cascade_res: u32,
    fadeDistScale: f64,
    dvs_supersample_enable: bool,
    gamma: f64,
    configversion: u16,
}
