use super::VideoConfig;

impl Default for VideoConfig {
    fn default() -> Self {
        Self {
            cl_gib_allow: false,
            cl_particle_fallback_base: 3,
            cl_particle_fallback_multiplier: 2,
            cl_ragdoll_maxcount: 0,
            cl_ragdoll_self_collision: true,
            mat_forceaniso: 1,
            mat_mip_linear: 0,
            stream_memory: 3_000_000,
            mat_picmip: 0,
            particle_cpu_level: 0,
            r_createmodeldecals: false,
            r_decals: 0,
            r_lod_switch_scale: 1.,
            shadow_enable: false,
            shadow_depth_dimen_min: 0,
            shadow_depth_upres_factor_max: 0,
            shadow_maxdynamic: 0,
            ssao_enabled: false,
            ssao_downsample: 3,
            modeldecals_forceAllowed: false,
            dvs_enable: false,
            dvs_gpuframetime_min: 15000,
            dvs_gpuframetime_max: 16500,
            defaultres: 1920,
            defaultresheight: 1080,
            fullscreen: true,
            nowindowborder: false,
            volumetric_lighting: false,
            mat_vsync_mode: false,
            mat_backbuffer_count: 1,
            mat_antialias_mode: 0,
            csm_enabled: false,
            csm_coverage: 1,
            csm_cascade_res: 1024,
            fadeDistScale: 1.,
            dvs_supersample_enable: false,
            gamma: 1.,
            configversion: 7,
            screen_height: 1920,
            screen_width: 1920,
            screen_refresh_rate: 60,
            letterbox_ratio: None,
        }
    }
}
